env:
   global:
     - CONAN_REFERENCE: "Pulsr.Window-win32/1.0"
     - CONAN_LOGIN_USERNAME: "strootje"
     - CONAN_USERNAME: "strootje"
     - CONAN_CHANNEL: "conan"
     - CONAN_REMOTES: "https://api.bintray.com/conan/conan-community/conan, https://api.bintray.com/conan/strootje/conan"
     - CONAN_UPLOAD: "https://api.bintray.com/conan/strootje/conan"

linux: &linux
   os: linux
   sudo: required
   language: python
   python: "3.6"
   services:
     - docker

osx: &osx
   os: osx
   language: generic

matrix:
   include:
      - <<: *linux
        env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40

install:
  - chmod +x .travis/install.sh
  - ./.travis/install.sh

script:
  - chmod +x .travis/run.sh
  - ./.travis/run.sh
